version: '3.9'

services:
  new_tb_api:
    build:
      context: ..
      target: production
      dockerfile: docker/Dockerfile
    container_name: new_tb_api
    volumes:
      - ../app:/tb/app
      - ../migrations:/tb/migrations
      - ../static:/tb/static
    env_file:
      - ../.env
    environment:
      - POSTGRES_HOST=new_tb_db
      - REDIS_HOST=new_tb_cache
    depends_on:
      - new_tb_db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    tty: true
    networks:
      - new_tb_network

  new_tb_db:
    image: postgres:15-alpine
    container_name: new_tb_db
    command: -p ${POSTGRES_PORT}
    volumes:
      - new_tb_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - new_tb_network

  new_tb_cache:
    image: redis:7-alpine
    container_name: new_tb_cache
    env_file: ../.env
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT} --include /usr/local/etc/redis/redis.conf
    volumes:
      - .././redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - new_tb_network

  new_nginx:
    build:
      context: ../nginx
    container_name: new_tb_nginx
    ports:
      - 5000:5000
    depends_on:
      - new_tb_api
    networks:
      - new_tb_network

volumes:
  new_tb_postgres_data:

networks:
  new_tb_network:
