version: '3.9'

services:
  tb_api:
    build:
      context: ..
      target: development
      dockerfile: docker/Dockerfile
      # args:
        # - HTTP_PROXY=http://antipov:911@proxy.bolid.ru:3128
        # - HTTPS_PROXY=http://antipov:911@proxy.bolid.ru:3128
    container_name: tb_api
    volumes:
      - ../app:/tb/app
      - ../migrations:/tb/migrations
      - ../static:/tb/static
    env_file:
      - ../.env
    environment:
      - POSTGRES_HOST=tb_db
      - REDIS_HOST=tb_cache
    depends_on:
      - tb_db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    tty: true
    networks:
      - tb_network

  tb_db:
    image: postgres:15-alpine
    container_name: tb_db
    command: -p ${POSTGRES_PORT}
    volumes:
      - tb_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - tb_network

  tb_cache:
    image: redis:7-alpine
    container_name: tb_cache
    env_file: ../.env
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - tb_network

  nginx:
    build:
      context: ./nginx
    container_name: tb_nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - tb_api
    networks:
      - tb_network

volumes:
  tb_postgres_data:

networks:
  tb_network:
