from app.consts.sports_types import SportsTypes

DEFAULT_DATA = [
    {
        "key": "gender",
        "label": "Пол",
        "type": "select",
        "options": ["Мужской", "Женский"],
        "required": True,
    },
    {
        "key": "position",
        "label": "Игровая позиция",
        "type": "text",
        "required": True,
    },
    {
        "key": "height",
        "label": "Рост",
        "type": "number",
        "required": True,
    },
    {
        "key": "weight",
        "label": "Вес",
        "type": "number",
        "required": True,
    },
    {
        "key": "age",
        "label": "Возраст",
        "type": "number",
        "required": True,
    },
    {
        "label": "Физическая подготовка",
        "type": "table",
        "rows_length": 6,
        "rows": [
            "Норматив",
            "Жим лежа(кг)",
            "Приседания(кг)",
            "10м(с)",
            "30м(с)",
            "Бронко",
        ],
        "columns_length": 4,
        "columns": ["Норматив", "Результат актуальный", "Относил. Сила", "Норма"],
        "cells": [
            {
                "key": "press__current",
                "row_index": 1,
                "column_index": 1,
                "type": "number",
                "required": True,
            },
            {
                "key": "press__relative",
                "row_index": 1,
                "column_index": 2,
                "type": "number",
                "required": True,
            },
            {
                "key": "press__standart",
                "row_index": 1,
                "column_index": 3,
                "type": "info",
                "placeholder": ">1.4",
            },
            {
                "key": "squat__current",
                "row_index": 2,
                "column_index": 1,
                "type": "number",
                "required": True,
            },
            {
                "key": "squat__relative",
                "row_index": 2,
                "column_index": 2,
                "type": "number",
                "required": True,
            },
            {
                "key": "squat__standart",
                "row_index": 2,
                "column_index": 3,
                "type": "info",
                "placeholder": ">1.7",
            },
            {
                "key": "ten__current",
                "row_index": 3,
                "column_index": 1,
                "type": "number",
                "required": True,
            },
            {
                "key": "ten__relative",
                "row_index": 3,
                "column_index": 2,
                "type": "number",
                "required": True,
            },
            {
                "key": "ten__standart",
                "row_index": 3,
                "column_index": 3,
                "type": "info",
                "placeholder": "Нап(Forwards). <1,70 Защит(Backs) <1,60",
            },
            {
                "key": "thirty__current",
                "row_index": 4,
                "column_index": 1,
                "type": "number",
                "required": True,
            },
            {
                "key": "thirty__relative",
                "row_index": 4,
                "column_index": 2,
                "type": "number",
                "required": True,
            },
            {
                "key": "thirty__standart",
                "row_index": 4,
                "column_index": 3,
                "type": "info",
                "placeholder": "Нап(Forwards). <4,20 Защит(Backs) <4,00",
            },
            {
                "key": "bron__current",
                "row_index": 5,
                "column_index": 1,
                "type": "time",
                "required": True,
            },
            {
                "key": "bron__relative",
                "row_index": 5,
                "column_index": 2,
                "type": "time",
                "required": True,
            },
            {
                "key": "bron__standart",
                "row_index": 5,
                "column_index": 3,
                "type": "info",
                "placeholder": "Нап(Forwards). <5:00 Защит(Backs) <4:40",
            },
        ],
    },
]


SURVEY_SPORTS_MAIN_DATA: dict[SportsTypes, list] = {
    SportsTypes.RUGBY: DEFAULT_DATA,
    SportsTypes.FOOTBALL: DEFAULT_DATA,
    SportsTypes.BASKETBALL: DEFAULT_DATA,
    SportsTypes.TENNIS: DEFAULT_DATA,
}
