"""add

Revision ID: 157a6adca03d
Revises: a2300a3b0293
Create Date: 2024-03-22 14:12:46.884980

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "157a6adca03d"
down_revision: Union[str, None] = "a2300a3b0293"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workouts", sa.Column("rest_time", sa.Integer(), nullable=False))
    op.add_column(
        "workouts", sa.Column("stress_questionnaire_time", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workouts", "stress_questionnaire_time")
    op.drop_column("workouts", "rest_time")
    # ### end Alembic commands ###
