""".///.

Revision ID: 1c26206b5860
Revises: babc6637a737
Create Date: 2024-03-14 14:12:33.896217

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c26206b5860"
down_revision: Union[str, None] = "babc6637a737"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workouts_pool", sa.Column("trainer_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "workouts_pool", "trainers", ["trainer_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workouts_pool", type_="foreignkey")  # type: ignore
    op.drop_column("workouts_pool", "trainer_id")
    # ### end Alembic commands ###
