"""add surveys

Revision ID: 38a72de528dc
Revises: fe80d6bf6c0c
Create Date: 2024-03-06 08:03:30.891754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38a72de528dc'
down_revision: Union[str, None] = 'fe80d6bf6c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_surveys',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('main_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('add_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sportsman_surveys',
    sa.Column('sportsman_id', sa.UUID(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['sportsman_id'], ['sportsmans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sportsman_surveys')
    op.drop_table('team_surveys')
    # ### end Alembic commands ###
