"""asd

Revision ID: 40d9c55427e4
Revises: 1c26206b5860
Create Date: 2024-03-14 15:40:08.414602

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40d9c55427e4"
down_revision: Union[str, None] = "1c26206b5860"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("exercises", sa.Column("workout_pool_id", sa.UUID(), nullable=False))
    op.drop_constraint("exercises_workout_id_fkey", "exercises", type_="foreignkey")
    op.create_foreign_key(
        None,
        "exercises",
        "workouts_pool",
        ["workout_pool_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("exercises", "workout_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercises",
        sa.Column("workout_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "exercises", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "exercises_workout_id_fkey",
        "exercises",
        "workouts",
        ["workout_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("exercises", "workout_pool_id")
    # ### end Alembic commands ###
