"""asd

Revision ID: 45dd486b52f9
Revises: c3a840646b67
Create Date: 2024-03-05 12:00:26.066859

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45dd486b52f9"
down_revision: Union[str, None] = "c3a840646b67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("sport_type", sa.String(), nullable=False))
    op.drop_column("trainers", "sport_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trainers",
        sa.Column("sport_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("teams", "sport_type")
    # ### end Alembic commands ###
