"""add repeat_id

Revision ID: 51b68bd188ea
Revises: 3e51fc17f612
Create Date: 2024-12-04 19:01:42.680072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b68bd188ea'
down_revision: Union[str, None] = '3e51fc17f612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('repeat_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'repeat_id')
    # ### end Alembic commands ###
