"""add remember_me

Revision ID: 562ea6afa0cf
Revises: 9d9584a4b4e9
Create Date: 2025-03-11 15:40:04.991292

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "562ea6afa0cf"
down_revision: Union[str, None] = "9d9584a4b4e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("remember_me", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "remember_me")
    # ### end Alembic commands ###
