"""..

Revision ID: 6178216870e1
Revises: 38a72de528dc
Create Date: 2024-03-09 10:56:26.165997

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6178216870e1"
down_revision: Union[str, None] = "38a72de528dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sportsman_surveys", sa.Column("update_it", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sportsman_surveys", "update_it")
    # ### end Alembic commands ###
