"""add created_at

Revision ID: 63204fe352f0
Revises: c81bd8dfd87f
Create Date: 2024-04-03 12:07:54.148427

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63204fe352f0"
down_revision: Union[str, None] = "c81bd8dfd87f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "health_questionnaires",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "stress_questionnaires",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stress_questionnaires", "created_at")
    op.drop_column("health_questionnaires", "created_at")
    # ### end Alembic commands ###
