"""remove_stress_quistionare_time

Revision ID: 721f90602146
Revises: de94460274d4
Create Date: 2025-03-20 17:55:17.089511

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "721f90602146"
down_revision: Union[str, None] = "de94460274d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workouts", sa.Column("price", sa.Integer(), nullable=False))
    op.drop_column("workouts", "stress_questionnaire_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workouts",
        sa.Column(
            "stress_questionnaire_time",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("workouts", "price")
    # ### end Alembic commands ###
