"""add_new_fields

Revision ID: 97211e928680
Revises: 721f90602146
Create Date: 2025-03-21 15:54:08.653724

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97211e928680"
down_revision: Union[str, None] = "721f90602146"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sportsmans_workouts", sa.Column("is_paid", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "sportsmans_workouts", sa.Column("is_attend", sa.Boolean(), nullable=False)
    )
    op.drop_constraint(
        "sportsmans_workouts_status_id_fkey", "sportsmans_workouts", type_="foreignkey"
    )
    op.drop_column("sportsmans_workouts", "status_id")
    op.drop_constraint(
        "trainers_workouts_status_id_fkey", "trainers_workouts", type_="foreignkey"
    )
    op.drop_column("trainers_workouts", "status_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trainers_workouts",
        sa.Column("status_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "trainers_workouts_status_id_fkey",
        "trainers_workouts",
        "workouts_statuses",
        ["status_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "sportsmans_workouts",
        sa.Column("status_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "sportsmans_workouts_status_id_fkey",
        "sportsmans_workouts",
        "workouts_statuses",
        ["status_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("sportsmans_workouts", "is_attend")
    op.drop_column("sportsmans_workouts", "is_paid")
    # ### end Alembic commands ###
