"""remove_team_name_and_sport_type

Revision ID: 9d9584a4b4e9
Revises: 51b68bd188ea
Create Date: 2025-03-03 15:45:24.214494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9584a4b4e9'
down_revision: Union[str, None] = '51b68bd188ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'name')
    op.drop_column('teams', 'sport_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('sport_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
