"""add visible

Revision ID: a2300a3b0293
Revises: fd5fb4b16d01
Create Date: 2024-03-21 14:54:59.605166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2300a3b0293'
down_revision: Union[str, None] = 'fd5fb4b16d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('is_visible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'is_visible')
    # ### end Alembic commands ###
