"""add comm and goal

Revision ID: b24ebf869317
Revises: 63204fe352f0
Create Date: 2024-04-25 13:14:23.819157

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b24ebf869317"
down_revision: Union[str, None] = "63204fe352f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workouts", sa.Column("comment", sa.String(), nullable=True))
    op.add_column("workouts", sa.Column("goal", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workouts", "goal")
    op.drop_column("workouts", "comment")
    # ### end Alembic commands ###
