"""...

Revision ID: babc6637a737
Revises: c8441ef98b28
Create Date: 2024-03-14 14:10:19.499979

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "babc6637a737"
down_revision: Union[str, None] = "c8441ef98b28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workouts_pool",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("estimated_time", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("workouts", sa.Column("workout_pool_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None,
        "workouts",
        "workouts_pool",
        ["workout_pool_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("workouts", "name")
    op.drop_column("workouts", "created_at")
    op.drop_column("workouts", "estimated_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workouts",
        sa.Column(
            "estimated_time",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "workouts",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "workouts", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "workouts", type_="foreignkey") # type: ignore
    op.drop_column("workouts", "workout_pool_id")
    op.drop_table("workouts_pool")
    # ### end Alembic commands ###
