"""change

Revision ID: c3a840646b67
Revises: fa18ba5aa0d8
Create Date: 2024-03-04 11:47:59.509267

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3a840646b67"
down_revision: Union[str, None] = "fa18ba5aa0d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sportsmans", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("sportsmans", sa.Column("middle_name", sa.String(), nullable=True))
    op.add_column("sportsmans", sa.Column("last_name", sa.String(), nullable=True))
    op.drop_column("sportsmans", "name")
    op.add_column("teams", sa.Column("name", sa.String(), nullable=False))
    op.add_column("trainers", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("trainers", sa.Column("middle_name", sa.String(), nullable=True))
    op.add_column("trainers", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column("trainers", sa.Column("sport_type", sa.String(), nullable=False))
    op.drop_column("trainers", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trainers", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("trainers", "sport_type")
    op.drop_column("trainers", "last_name")
    op.drop_column("trainers", "middle_name")
    op.drop_column("trainers", "first_name")
    op.drop_column("teams", "name")
    op.add_column(
        "sportsmans",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("sportsmans", "last_name")
    op.drop_column("sportsmans", "middle_name")
    op.drop_column("sportsmans", "first_name")
    # ### end Alembic commands ###
