"""add health

Revision ID: c81bd8dfd87f
Revises: 97e7bee71c27
Create Date: 2024-04-03 11:55:26.224782

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c81bd8dfd87f"
down_revision: Union[str, None] = "97e7bee71c27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_questionnaires",
        sa.Column("sportsman_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["sportsman_id"], ["sportsmans.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "stress_questionnaires", "text", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stress_questionnaires", "text", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_table("health_questionnaires")
    # ### end Alembic commands ###
