"""asd

Revision ID: c8441ef98b28
Revises: 728809400e03
Create Date: 2024-03-09 13:18:00.166834

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8441ef98b28"
down_revision: Union[str, None] = "728809400e03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sportsman_surveys", sa.Column("team_survey_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "sportsman_surveys",
        "team_surveys",
        ["team_survey_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sportsman_surveys", type_="foreignkey")
    op.drop_column("sportsman_surveys", "team_survey_id")
    # ### end Alembic commands ###
