"""add_local_sportsman

Revision ID: de94460274d4
Revises: 562ea6afa0cf
Create Date: 2025-03-13 18:07:18.282553

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de94460274d4"
down_revision: Union[str, None] = "562ea6afa0cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("sportsmans", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "sportsmans", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sportsmans", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("sportsmans", "email", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
