"""add visible

Revision ID: fd5fb4b16d01
Revises: 40d9c55427e4
Create Date: 2024-03-18 13:25:58.058475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5fb4b16d01'
down_revision: Union[str, None] = '40d9c55427e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts_pool', sa.Column('is_visible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts_pool', 'is_visible')
    # ### end Alembic commands ###
