"""add avatar

Revision ID: fe80d6bf6c0c
Revises: 45dd486b52f9
Create Date: 2024-03-05 12:37:58.043863

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe80d6bf6c0c"
down_revision: Union[str, None] = "45dd486b52f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sportsmans", sa.Column("avatar_uri", sa.String(), nullable=True))
    op.add_column("trainers", sa.Column("avatar_uri", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trainers", "avatar_uri")
    op.drop_column("sportsmans", "avatar_uri")
    # ### end Alembic commands ###
