"""add trainer support in exercises types

Revision ID: ff4e9062f5c8
Revises: b24ebf869317
Create Date: 2024-05-13 10:27:36.917772

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff4e9062f5c8"
down_revision: Union[str, None] = "b24ebf869317"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercises_types", sa.Column("description", sa.String(), nullable=False)
    )
    op.add_column(
        "exercises_types", sa.Column("is_basic", sa.Boolean(), nullable=False)
    )
    op.add_column("exercises_types", sa.Column("trainer_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "exercises_types", "trainers", ["trainer_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "exercises_types", type_="foreignkey")
    op.drop_column("exercises_types", "trainer_id")
    op.drop_column("exercises_types", "is_basic")
    op.drop_column("exercises_types", "description")
    # ### end Alembic commands ###
